apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment
  namespace: django-crud-devops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysqlpod

  template:
    metadata:
      labels:
        app: mysqlpod
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:9.7

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: employeesdb

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-volume