apiVersion: v1
kind: Secret

metadata:
  name: django-secret
  namespace: django-crud-devops


stringData:
  DJANGO_SECRET_KEY: "djangosecretkey123"
  DB_USER: "employeeuser"
  DB_PASSWORD: "employeepassword"